title: Default
fields:
  -
    handle: content
    field:
      type: markdown
      display: Content
  -
    handle: author
    field:
      type: users
      display: Author
      default: current
      max_items: 1
  -
    handle: template
    field:
      type: template
      display: Template
